# Generated by Django 5.1.4 on 2025-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('yet_to_start', 'Yet to Start'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='yet_to_start', max_length=20),
        ),
    ]
