# Generated by Django 5.1.4 on 2025-02-10 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
