# Generated by Django 5.1.7 on 2025-03-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
